### ISSUE TITLE
Make profile Rules ready

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/profile#13]
In order for Rules to be able to access profiles, this module needs to do three things:
- Include a value for `'metadata controller class'` in the entity definition inside `profile_entity_info()`
- Extend `EntityDefaultMetadataController`, with a class called something like `ProfileMetadataController`.
- Add this new class to the autoload_info function

This can be done without the need to make Entity Plus a dependency. When you enable Rules, Entity Plus will be enabled and will pick up the  new Metadata class and will allow Rules to "see" the Profiles and all their fields and properties (since they are entities).

A good model is shown in the D7 version - Profile2

**Comment by docwilmot** [comment]
Was D7 Profile 2 Rules-ready? 
Edit: ignore that. I didnt reach the last line of the above 😞

**Comment by argiepiano** [comment]
Actually there is one more step. Rules will only pick up custom entities if they use `EntityPlusController`. Since Profile uses core's `EntityDatabaseStorageController`, Rules will not pick it up.

The issue is that, if we make `EntityPlusController` the profile entity controller, then we MUST require Entity Plus as a dependency of Profile.

This may be a problem with Rules, but I'd have to look more closely at why the core controller is not picked up by Rules. 

In the meantime, what are your thoughts, @bugfolder? It's a shame that Profile is not picked up by Rules at this point. Would you be open to adding Entity Plus as a requirement? 

I'll submit a PR in a minute with these changes, just in case you think it's worth it

When Profile is picked up by Rules, it shows in the Events list:

<img width="346" alt="Screen Shot 2022-10-03 at 8 50 46 PM" src="https://user-images.githubusercontent.com/9938978/193724498-b3849020-1ff1-4bd7-b32c-eda2d0d38692.png">

**Comment by argiepiano** [comment]
PR #14 

Please test thoroughly. I've change the controller to use `EntityPlusController`. There shouldn't be any issues with this, as the controllers' APIs overlap.

One more benefit of depending on Entity Plus: you can enable Entity Tokens and access Profile through chained user tokens, as in `[user:profile_main:FIELD_NAME]`

**Comment by bugfolder** [comment]
> One more benefit of depending on Entity Plus: you can enable Entity Tokens and access Profile through chained user tokens...

I was going to raise this as a possible solution approach in the discussion in https://github.com/backdrop-contrib/profile/issues/12. Having recently found Token Block to be incredibly useful, I think this would be a great upgrade to Profile.

**Comment by argiepiano** [comment]
An alternative, if changing the controller is not desirable, is to implement all rules hooks manually (e.g. hook_rules_events_info() etc) rather than letting Rules and Entity Plus automatically create those info arrays. 

BTW, Entity Tokens will still provide all tokens even if we keep the core controller.

**Comment by argiepiano** [comment]
> BTW, Entity Tokens will still provide all tokens even if we keep the core controller.

Meaning that you should still be able to use Token Block to access Profile properties and fields (without merging this PR) if you enable Entity Tokens... I think. Haven't tested it 

[EDIT] Actually, no. In order to access Profile tokens through chaining ([user:profile_main:etc] you would need to either change controller to EntityPlusController, OR define entity property info by implementing Entity Plus' hook_entity_property_info(). The issue is that the relationship between profile and user entities is handled by a E+ metadata property (formerly Entity API).

**Comment by bugfolder** [comment]
Always an issue with adding a dependency is breaking an existing site if someone just upgrades to the latest version without reading the release notes. So I'm wondering if it's possible to do this in two stages:

In the first stage, we'd add the new functionality but in such a way that the old functionality is preserved if Entity Plus isn't present; AND we'd add a warning on the status page that Entity Plus is recommended and will be required in the next version, thereby giving site builders a more prominent heads-up (and an ongoing nag) to install EP. (If EP is installed, the warning goes away.)

And then, after a decent interval, we could remove the conditional code and make EP a hard dependency in the next minor version.

I've not looked into the PR enough to tell whether this approach is feasible, but @argiepiano, do you think it is?

**Comment by argiepiano** [comment]
@bugfolder, I think it's possible to do what you describe. But I'm leaning toward finding a solution that doesn't require Entity Plus. It's possible to keep the current controller, and implement all Rules hooks manually (it's not that many). This is basically the same thing we did with Views for Profile - implemented those hooks manually rather than letting Entity Plus create those automatically. 

There are a couple of things we still need from this PR: the class `ProfileMetadataController` (which is only used when Rules or Entity Tokens + Entity Plus are enabled), and adding that to the autoloader.

In addition, I've been experimenting with Token Block to provide a solution to #12. It's totally possible! But we need `ProfileMetadataController` too for that. So this PR will solve several issues. 

I'll modify this PR to remove the proposed E+ dependency and add the Rules hooks.

**Comment by argiepiano** [comment]
Or... here's another idea (since manually creating all those hooks is very laborious 😄 ).

We could implement `hook_entity_info_alter` and switch to the core controller if Entity Plus is not installed (or vice versa).

Since Rules requires Entity Plus, as soon as a user installs rules, Profile will automatically start using the E+ controller with all its benefits. What do you think, @bugfolder?

**Comment by argiepiano** [comment]
I've modified the PR to use EntityPlusController only if E+ is enabled (through a hook_entity_info_alter()).

I've tested it and it works beautifully. As soon as Rules/E+ are enabled, magic happens: all Rules actions, conditions and events now "see" Profile. Plus, if you enable Entity Tokens you can use chained user tokens to access profile fields and properties (but you also need to patch Profile with #15)

**Comment by bugfolder** [comment]
> Since Rules requires Entity Plus, as soon as a user installs rules, Profile will automatically start using the E+ controller with all its benefits. What do you think?

That sounds ideal.

I'm about to go off on a trip, so I will probably not get to be able to test this for several days. But I'll add it to my to-do list soon.

**Comment by bugfolder** [comment]
Tested and works! Thanks, @argiepiano!
