### ISSUE TITLE
Profile entity class does not implement `bundle()` method

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/profile#15]
This is causing issues with token replacement when using Entity Token to access tokens such as `[user:profile_main:FIELD_NAME]`. Basically the bundle method should return the profile type, which in turn it's used to get the field value for token replacement.

It's an easy fix. PR coming

**Comment by argiepiano** [comment]
PR #16 submitted.

**Comment by bugfolder** [comment]
Works! Thanks, @argiepiano!
