### ISSUE TITLE
Some registration emails are sent twice

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/profile#18]
Some of the emails sent during a registration process are sent twice. Disabling profile module fixes it.

**Comment by robertgarrigos** [comment]
I see that this function profile_form_before_user_register_submit_handler(), added because of a bug with profile 2 for drupal already fixed (https://www.drupal.org/node/1097684), disables the notifications emails. Then, the next function profile_form_after_user_register_submit_handler() sends them. Provably the first one don't actually disable the mail and they get sent twice.

**Comment by bugfolder** [comment]
Verified the bug, tested the patch and it fixes the problem. Thanks @robertgarrigos!

**Comment by oriolroger** [comment]
Hi. We are still getting duplicated emails sent to new users, once they're registered; we've noticed that the core module user.module is first sending the email, in `function user_register_submit($form, &$form_state)`, and then the Profile module is sending again the same email, in `function profile_form_after_user_register_submit_handler(&$form, &$form_state)`.

Actually, we don't see why the Profile module needs to send user emails, if that's already managed by default in core. We're currently running version Profile2 7.x-1.3 in a Drupal 7 site, and it's working correctly.

Do you manage to know why were these functions (`profile_form_before_user_register_submit_handler` and `profile_form_after_user_register_submit_handler`) added?

Thanks a lot.

**Comment by bugfolder** [comment]
> Do you manage to know why were these functions (profile_form_before_user_register_submit_handler and profile_form_after_user_register_submit_handler) added?

I know why they were added; it's explained in the docblock for `profile_form_before_user_register_submit_handler()`:

```
/**
 * User registration form submit handler that executes right before
 * user_register_submit().
 *
 * This callback disables the notification emails during the execution of the
 * user_register_submit() callback. The reason for this is that we want to
 * support profile tokens in emails during registration, and there is no other
 * proper way to do this. See https://drupal.org/node/1097684.
 *
 * @see profile_form_after_user_register_submit_handler()
 * @see user_register_submit()
 * @see profile_attach_form()
 */
function profile_form_before_user_register_submit_handler(&$form, &$form_state) {
...
```

In theory, the "before" version disables the sending in `user_register_submi_handler()`, then does its own sending (then re-enables the sending). But clearly, the disabling isn't working for you. I"ll look into it further. Any further information you could provide about your settings would be helpful.

**Comment by oriolroger** [comment]
Could the problem be that in `function profile_form_after_user_register_submit_handler`, the first thing it does is to change the notifications settings back, and the next thing is to send the emails? That way, the notification emails are always sent, even if we previously have disabled notifications.

**Comment by bugfolder** [comment]
I think the logic of the order in that function is correct, and it actually shouldn't matter, since the decision on sending the emails in the function depends on the values in the form (`$form_state['values']`).

I've been trying to reproduce the double-emails, and have been unable to do so; I get zero or one email, per the config settings. Can you give a description of your user account settings and a sequence of actions that results in double emails being sent?

**Comment by oriolroger** [comment]
Thanks @bugfolder. I'll try it, but TBH we have a quite complicated intranet, and is not easy to give details of the actions followed. What we noticed is that an email is first sent in user.module (`function user_register_submit()`), and then the same validations are checked, and same email is sent, in profile.module(`function profile_form_after_user_register_submit_handler()`). 

As it says in the comments of this function, `this is a trimmed version of user_register_submit() callback`.

But again, we'll try to dig into the process, to find if our system is doing something that it shouldn't.

Thanks again.

**Comment by argiepiano** [comment]
@oriolroger do you have Login Toboggan enabled? Have you considered the possibility that this may be causing the issue? Both logintoboggan and profile use `hook_form_user_profile_form_alter()` in similar ways. Profile must alter the form after Login Toboggan. Perhaps what's happening here is that this is not happening in that order.

**Comment by oriolroger** [comment]
Thanks @argiepiano, no I haven't Login Toboggan enabled. But I've seen that Profile module is replacing the default `user_register_submit` callback with `logintoboggan_user_register_submit`, in case this module is enabled.

**Comment by argiepiano** [comment]
Do you have any other module that implements `hook_form_user_profile_form_alter()`? Perhaps a custom module? Github lists 4 modules that implement it: https://github.com/search?q=org%3Abackdrop-contrib%20hook_form_user_profile_form_alter&type=code

**Comment by argiepiano** [comment]
Mimemail also implements it (strange that it did not come up in the search)

**Comment by argiepiano** [comment]
Oh, there are actually quite a few others: https://github.com/search?q=org%3Abackdrop-contrib+_form_user_profile_form_alter&type=code

**Comment by bugfolder** [comment]
Can you check whether `profile_form_before_user_register_submit_handler` is getting called, by enabling the Devel module and inserting a call `dpm('profile_form_before_user_register_submit_handler');` into `profile_form_before_user_register_submit_handler `? 

In theory, `profile_form_before_user_register_submit_handler ` should disable the notifications sent by `user_register_submit` (in favor of sending them via `profile_form_after_user_register_submit_handler`).

**Comment by argiepiano** [comment]
Here's another thought. Those core emails are temporarily disabled by `$config->set($register_op, FALSE);`  inside `profile_form_before_user_register_submit_handler()`. This temporary setting is never saved (there is no `$config->save()`, as this function trusts that `system.core.json` has static cache enabled, and that this setting will persist until it reaches `user_register_submit()`.

But perhaps there is a contrib module that either disables static cache for this config file, OR that clears the config static  cache.

This may be hard to debug, though. As a first step I would temporarily add a `$config->save()` after `$config->set($register_op, FALSE);` and after `$config->set($register_op, TRUE);`. This will rely on disk rather than static cache for these temporary changes. Then try again. If you find that this solves the problem, the next step is to figure out where that static cache is being cleared.

**Comment by bugfolder** [comment]
That sounds pretty plausible. If saving the config does fix the problem, sounds like that would be an appropriate bulletproofing fix to add to this module. There's a small cost to add the write-to-disk, but this is not a frequent event.

**Comment by oriolroger** [comment]
Thanks @argiepiano, your solution totally worked for us. We've just added the `$config->save()` command after `$config->set()`, both in the _before_ and _after_ functions, and now I don't get any duplicated email. The email is only sent in the function profile_form_after_user_register_submit_handler().

Thanks again to @argiepiano and @bugfolder for looking into this.
