### ISSUE TITLE
Add access control to profiles?

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/profile#2]
I have a class of users that need some profile data attached to their account, but I would like to prevent them from editing that profile data.  How hard would it be to add some basic access controls to Profiles?

**Comment by docwilmot** [comment]
I dont know how hard, but dont think I can find out right now, sorry. You may need to write some code to try and override/alter something. Vague, sorry, but not sure how to help with this.

**Comment by sentaidigital** [comment]
A `hook_menu_alter()` to replace the `access callback` did it.
