### ISSUE TITLE
Public $langcode in Profile Entity class

### ISSUE THREAD

**Issue by oriolroger** [backdrop-contrib/profile#23]
Hi. We're getting some warnings from other modules and core, when they access the Profile entity class (defined in profile.entity.inc). They try to get the $langcode variable, but it's not declared in the Profile class. Shouldn't it be declared there? The same as we have for other entities, like Node, File, User, Taxonomy and Comment.

I've added this code in the Profile class declaration, and all the warnings have disappeared:

```
/**
 * The language under which the profile item is stored.
 *
 * @var string
 */
public $langcode = LANGUAGE_NONE;
```

Thanks!

**Comment by argiepiano** [comment]
There is a bigger issue with profile (inherited from D7): they are not translatable. See [this](https://www.drupal.org/project/profile2/issues/1966640). Adding the property will stop the warnings, but the schema of the profile entity does not store `langcode`, and therefore the entity is not translatable.

I believe in D7 they managed to make at least the Profile2 labels translatable (that is, the name of the profile type, as in "personal profile", "professional profile" etc). This was done, I believe, by depending on Entity API (Entity Plus in Backdrop) and adding metadata and callbacks in `modules/profile2_i18n.module`.

So, as a quick fix, the change above would be fine to merge, but in the long run, we should consider making profile entities translatable.

**Comment by bugfolder** [comment]
Code change is merged in, a follow-on issue is https://github.com/backdrop-contrib/profile/issues/25.
