### ISSUE TITLE
Forcing form_alter implementation to the end of queue renders module pretty useless.

### ISSUE THREAD

**Issue by akarso** [backdrop-contrib/profile#3]
https://forum.backdropcms.org/forum/hookformalter-and-missing-profile-data

To recap:
function profile_module_implements_alter()  forces execution of profile_form_user_register_form_alter() to be the last on the list of implementations. Hence one cannot alter user profile, since there are no data yet, at the time of calling mymodule_form_alter().

Use case: I have custom user profiles, which I'd like to change at the edit screen. I can't, because they are not attached yet.

**Comment by docwilmot** [comment]
Cant help this unfortunately.
