### ISSUE TITLE
Change "Add Profile" to "Add Profile Type"

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/profile#31]
The language here suggests that I'm creating a specific profile, not a profile type. 

![image](https://github.com/backdrop-contrib/profile/assets/3144571/be8487b4-8fc9-4649-abda-c1dfe7631b1d)

The save button is more specific.

![image](https://github.com/backdrop-contrib/profile/assets/3144571/f8749c41-8555-479e-80d4-4e7ea72c9bee)

**Comment by stpaultim** [comment]
Decided to change the page title as well to Profile types. This feels consistent with other similar pages, such as Content types. 

![image](https://github.com/backdrop-contrib/profile/assets/3144571/d887539a-64b2-4565-971e-ca64a183514f)

See attached PR.

**Comment by stpaultim** [comment]
One more small change.

Changes page title from "Profile" to "Add profile type"

BEFORE:

![image](https://github.com/backdrop-contrib/profile/assets/3144571/a81a9f99-e5c1-4c64-af1b-0b58e4bda3d2)

AFTER:

![image](https://github.com/backdrop-contrib/profile/assets/3144571/6ebe8577-1e85-4388-be24-072b20e5f36a)

**Comment by bugfolder** [comment]
Agreed, thanks for the PR.
