### ISSUE TITLE
Uncaught Error: Class 'ProfileMetadataController' not found

### ISSUE THREAD

**Issue by paucku** [backdrop-contrib/profile#34]
I really don't remember what I did beforehand. But now I have this error on my Backdrop CMS site:

`Uncaught Error: Class 'ProfileMetadataController' not found`

The site is nonfunctional – cannot access any of its pages. However I think am still logged in.

I tried to clear the cache by invoking this URL: https://example.com/core/rebuild.php

I've found that the class ProfileMetadataController is found in the Profile module. So I decided to remove the module mannually by deleting its folder in modules folder. But after removing the module the site is still nonfunctional. Only the error changed:

`Fatal error: Uncaught Error: Class 'ProfileMetadataController' not found in /my-site-home/modules/entity_plus/entity_plus.module:133 Stack trace: #0 /my-site-home/core/includes/module.inc(975): entity_plus_entity_property_info() #1 /my-site-home/modules/entity_plus/includes/entity_plus.property.inc(37): module_invoke_all('entity_property...') #2 /my-site-home/modules/entity_plus/views/entity_plus.views.inc(445): entity_plus_get_property_info('paragraphs_item') #3 /my-site-home/modules/entity_plus/views/entity_plus.views.inc(387): EntityPlusDefaultViewsController->schema_fields() #4 /my-site-home/modules/entity_plus/views/entity_plus.views.inc(33): EntityPlusDefaultViewsController->views_data() #5 /my-site-home/core/includes/module.inc(975): entity_plus_views_data() #6 /my-site-home/core/modules/views/includes/cache.inc(89): module_invoke_all('views_data') #7 /my-site-home/core/modules/views/includes/cache.inc(74): _views_fetch_data_build() #8 /home/pr in /my-site-home/modules/entity_plus/entity_plus.module on line 133`

Do you have any idea on how to debug it so I can reach the source of the problem?

**Comment by paucku** [comment]
Update: After I deleted the module Entity Plus the site became functional but still get the error when I want to add content:
`Class 'EntityPlusController' not found`

For some contetnt types as Cards and Webform there is not error. But there is error for all of the other content types.

I suspect there is a problem with Paragraphs or some entity reference.

**Comment by argiepiano** [comment]
You should not remove Entity Plus, as it's needed by Paragraphs. You should put it back into the modules folder.

The original error may be related to cache problems. You said that you cleared caches by invoking  https://example.com/core/rebuild.php , but that file is not part of Backdrop. The only ways to clear caches are by using the UI, or by using `bee cc all` in the shell command line (you have to install bee on your server).

There are a few instance when clearing caches won't even work. In those cases you have to clear (truncate) the cache tables directly in the database. 

PS: you can also try example.com/update.php - I believe that will also clear the caches.

**Comment by paucku** [comment]
Now after I had a functional site I saw that the Profile module was disabled. Maybe because in attempt to solve the issue I removed it. Now I enabled it. During this enabling the system told me that some modules which depend on Entiy Plus will be disabled (like paragraphs).

Now I have no error. But I also have no functining paragraphs :(

**Comment by argiepiano** [comment]
> During this enabling the system told me that some modules which depend on Entiy Plus will be disabled (like paragraphs).

Have you tried to re-enable them after restoring the `entity_plus` folder to `modules`?

**Comment by paucku** [comment]
> You should not remove Entity Plus, as it's needed by Paragraphs. You should put it back into the modules folder.

Now I returned back the Entity Plus and the site now is functinal and working. No problems when I add content. 

I really don't know why the error was: `Class 'ProfileMetadataController' not found`

It doesn't seem anything related.

**Comment by argiepiano** [comment]
Glad it's working again. But you should try running update.php and/or clearing the caches to be sure things are really back to normal

**Comment by paucku** [comment]
> Glad it's working again. But you should try running update.php and/or clearing the caches to be sure things are really back to normal

I tried to clear the cach before by running https://example.com/core/rebuild.php but the site still was nonfunctional after that.  

Now in the end I cleared the cache many times to be sure. But it worked even when I didn't clear the cache.

**Comment by paucku** [comment]
> Glad it's working again. But you should try running update.php and/or clearing the caches to be sure things are really back to normal

Now I understand you. Yes, I've just invoked https://example.com/core/update.php and everithing is working fine :) Thank you very much!
