### ISSUE TITLE
Profile Fields are not seen in Views

### ISSUE THREAD

**Issue by TheMetMan** [backdrop-contrib/profile#4]
I am using Backdrop version 1.15.x-dev and Profile version 1.x-1.0.5
I am trying to use a View to display a couple of fields from a Profile I have created for one Role of my users. I am not talking about the standard Profile a user gets when getting a new account, but one I have created using the Profile Module.
I have created a view with an Unformatted list of Fields. I have also tried the other choices eg Table.
When I go to  add a Field, nowhere is there the choice of Profile just Content, File Usage, Global, User Account and Webform fields.
Why does it not show the Profiles I have created? These contain several fields, and I would like only 3 of them.
Is there a way to chose the Display Mode from a View of Profiles, because I have created a Display Mode to show only the fields I want, but cannot seem to find how to show a Profile in Views.
I have asked on the Forum, and it has been suggested that this is not yet supported. Selecting a User as the source, the Profile fields are not visible.

**Comment by bugfolder** [comment]
Hi @TheMetMan, the Forum commenter is correct; Profile has no support for Views (yet), as was the case with its Drupal 7 equivalent, the Profile2 module. It would certainly be a nice addition though. I'll leave this issue open, but am labeling it as a feature request.

**Comment by tfpkiii** [comment]
@bugfolder That's not quite true about Profile2 in D7. I was (and can) use the Views "Add Relationships" function to link the Profile2 entity to the current User in Views, which used the UID as the key. With this setup, the fields from Profile2 were accessible in the Views "Add Field" box. Bit disappointed this isn't the case in the BD version

**Comment by bugfolder** [comment]
I'll see if I can add it.

**Comment by tfpkiii** [comment]
I'm not as conversant with the underpinnings of BD as D7, but does the hook_views_data() exist in BD? If so, it might be relatively simple to define a "join" relationship. I've used this in the past to link entities through Views but not sure how it would work here.

**Comment by argiepiano** [comment]
I have created a PR that adds Views support for profile. See #10
