### ISSUE TITLE
Upgrading from Drupal: Profile and Profile2 data not carried over

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/profile#5]
In upgrading an existing site that has both Profile and Profile2 data, neither type of profile is showing up in the Profile module after upgrade. Was upgrading (from either D7 module) intended to be supported?

**Comment by bugfolder** [comment]
I've prepared a hook_update_N() that will migrate existing Profile2 data from D7. (It does not migrate existing D7 Profile data.)

**Comment by herbdool** [comment]
@bugfolder I've added my comments on the PR. Overall looks good.

**Comment by herbdool** [comment]
I've merged your PR. Do you have write access to this project? If not @klonos or @jenlampton can fix it.

**Comment by bugfolder** [comment]
I don't have write access, so  @klonos or @jenlampton, please provide if possible. Thanks!

**Comment by bugfolder** [comment]
Access added, thanks! Have created a new release, closing this issue.
